name: Release Tag

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag_and_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get Pull Request title
        id: pr_title
        run: echo "::set-output name=title::${{ github.event.pull_request.title }}"

      - name: Extract version from PR title
        id: extract_version
        run: |
          VERSION=$(echo "${{ steps.pr_title.outputs.title }}" | grep -oP '(?<=Version: ).*')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$VERSION"

      - name: Create new tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout release branch
        run: git checkout release

      - name: Update package.json version
        run: |
          jq --arg version "${{ env.VERSION }}" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json

      - name: Commit changes
        run: |
          git add package.json
          git commit -m "Update package.json to version ${{ env.VERSION }}"

      - name: Merge tag into release branch
        run: git merge ${{ env.VERSION }} --no-ff -m "Merge tag ${{ env.VERSION }} into release branch"
      
      - name: Push changes to release branch
        run: git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}